import { NextRequest, NextResponse } from 'next/server';
import { auth } from '@/lib/auth';
import { headers } from 'next/headers';
// import connectDB from '@/lib/db';
import User from '@/models/User';
import Quest from '@/models/Quest';

export async function POST(req: NextRequest) {
  try {
    const session = await auth.api.getSession({
      headers: await headers(),
    });

    if (!session) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
    }

    await connectDB();
    
    const user = await User.findOne({ email: session.user.email });
    if (!user) {
      return NextResponse.json({ error: 'User not found' }, { status: 404 });
    }

    const body = await req.json();
    const { calendar, todoList, pastPerformance } = body;

    const completedQuests = await Quest.find({ 
      userId: user._id,
      completed: true 
    }).sort({ completedAt: -1 }).limit(20);

    const avgDifficulty = completedQuests.length > 0 
      ? completedQuests.reduce((acc, q) => acc + (q.difficulty || 1), 0) / completedQuests.length 
      : 1;

    const recentStreaks = completedQuests.filter(q => {
      const daysDiff = Math.floor((Date.now() - new Date(q.completedAt).getTime()) / (1000 * 60 * 60 * 24));
      return daysDiff <= 7;
    }).length;

    const performanceScore = Math.min(5, Math.floor((recentStreaks / 7) * 5) + 1);

    const generatedQuests = [];

    if (calendar && calendar.length > 0) {
      for (const event of calendar.slice(0, 3)) {
        const difficulty = Math.max(1, Math.min(5, Math.round(avgDifficulty)));
        generatedQuests.push({
          title: `Prepare for: ${event.title}`,
          description: `Get ready for your ${event.title} scheduled on ${event.date}`,
          category: 'Focus',
          difficulty,
          xpReward: difficulty * 50,
          coinReward: difficulty * 10,
          type: 'daily',
          autoGenerated: true,
          source: 'calendar'
        });
      }
    }

    if (todoList && todoList.length > 0) {
      for (const todo of todoList.slice(0, 3)) {
        const difficulty = Math.max(1, Math.min(5, Math.round(avgDifficulty)));
        generatedQuests.push({
          title: todo.title,
          description: todo.description || `Complete: ${todo.title}`,
          category: 'Focus',
          difficulty,
          xpReward: difficulty * 50,
          coinReward: difficulty * 10,
          type: 'daily',
          autoGenerated: true,
          source: 'todo'
        });
      }
    }

    const performanceQuests = [
      {
        title: 'Morning Power Hour',
        description: 'Complete 1 hour of focused work in the morning',
        category: 'Focus',
        difficulty: performanceScore,
        xpReward: performanceScore * 60,
        coinReward: performanceScore * 15,
        type: 'daily',
        autoGenerated: true,
        source: 'performance'
      },
      {
        title: 'Skill Builder',
        description: 'Practice a skill for 30 minutes',
        category: 'Creativity',
        difficulty: Math.max(1, performanceScore - 1),
        xpReward: Math.max(1, performanceScore - 1) * 50,
        coinReward: Math.max(1, performanceScore - 1) * 12,
        type: 'daily',
        autoGenerated: true,
        source: 'performance'
      }
    ];

    generatedQuests.push(...performanceQuests);

    for (const questData of generatedQuests) {
      const existingQuest = await Quest.findOne({
        userId: user._id,
        title: questData.title,
        completed: false
      });

      if (!existingQuest) {
        await Quest.create({
          ...questData,
          userId: user._id,
          createdAt: new Date()
        });
      }
    }

    return NextResponse.json({ 
      success: true, 
      generated: generatedQuests.length,
      performanceScore,
      message: `Generated ${generatedQuests.length} personalized quests!`
    });

  } catch (error: any) {
    console.error('Quest generator error:', error);
    return NextResponse.json(
      { error: 'Failed to generate quests', details: error.message },
      { status: 500 }
    );
  }
}

export async function GET(req: NextRequest) {
  try {
    const session = await auth.api.getSession({
      headers: await headers(),
    });

    if (!session) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
    }

    await connectDB();
    
    const user = await User.findOne({ email: session.user.email });
    if (!user) {
      return NextResponse.json({ error: 'User not found' }, { status: 404 });
    }

    const autoGeneratedQuests = await Quest.find({
      userId: user._id,
      autoGenerated: true,
      completed: false
    }).sort({ createdAt: -1 });

    return NextResponse.json({ quests: autoGeneratedQuests });

  } catch (error: any) {
    console.error('Get auto quests error:', error);
    return NextResponse.json(
      { error: 'Failed to get auto quests', details: error.message },
      { status: 500 }
    );
  }
}
